### ISSUE TITLE
Wrong number of watchers

### ISSUE THREAD

**Issue by metalmatze** [infinityworksltd/github-exporter#13]
I quickly tested this exporter and found that the number of watchers is wrong.
Stars is ok, but gitea has 133 watchers. :wink: 
```
github_repo_watchers{private="false",repo="gitea",user="go-gitea"} 2527.0
github_repo_stars{private="false",repo="gitea",user="go-gitea"} 2527.0
```

**Comment by alexellis** [comment]
@Rucknar I came here to raise the same issue, so 👍 from me.

**Comment by alexellis** [comment]
@metalmatze you can use my fork / image to get a fix. Hopefully Ed will merge/test it soon.
