### ISSUE TITLE
Rate limit checks fail when there is no rate limiting

### ISSUE THREAD

**Issue by bmanuel** [infinityworksltd/github-exporter#17]
I am trying to use this exporter against a GitHub Enterprise instance. This server does not have rate limiting enabled, which appears to be causing the following error when checking for a rate limit: `Error gathering Data from remote API: strconv.ParseFloat: parsing "": invalid syntax`.

**Comment by bmanuel** [comment]
Here is the output of curl to the rate limit api. Some details have been removed for privacy.

```
curl -v https://server/api/v3/rate_limit
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to server (x.x.x.x) port 443 (#0)
> GET /api/v3/rate_limit HTTP/1.1
> Host: server
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: GitHub.com
< Date: Tue, 09 May 2017 21:24:57 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 122
< Status: 404 Not Found
< Cache-Control: no-cache
< X-GitHub-Media-Type: github.v3
< Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
< Access-Control-Allow-Origin: *
< X-GitHub-Request-Id: 8f609e15-d338-4927-bd8f-ea969a18b96d
< Content-Security-Policy: default-src 'none'
< Strict-Transport-Security: max-age=31536000; includeSubdomains
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-XSS-Protection: 1; mode=block
<
{
  "message": "Rate limiting is not enabled.",
  "documentation_url": "https://developer.github.com/enterprise/2.8/v3"
}
* Curl_http_done: called premature == 0
* Connection #0 to host server left intact
```

**Comment by Rucknar** [comment]
Thanks for the heads up @bmanuel.

I've not had the ability to test against GitHub Enterprise, only the cloud instance.
I'll have a look at making the code for this passively fail and to log out the error only.

**Comment by Rucknar** [comment]
I've just pushed an image to test `infinityworks/github-exporter:04`. Would you mind giving it a once over? If all looks good i'll look to merge today.

**Comment by bmanuel** [comment]
@Rucknar Thanks for the quick fix. It appears to be working as expected.
