### ISSUE TITLE
Bug - Ignore invalid repos/orgs, log out and continue

### ISSUE THREAD

**Issue by Rucknar** [infinityworksltd/github-exporter#4]
As above, currently the script fails poorly.

**Comment by alexellis** [comment]
I've also seen this error - what do you mean by log out?

You can either crash/stop (which I think is a good option because it means there's bad config) or give a graceful error, and expose that as a new metric. It has to be surfaced somehow.

**Comment by Rucknar** [comment]
resolved by #15
