### ISSUE TITLE
Missing private repo stats?

### ISSUE THREAD

**Issue by hairyhenderson** [infinityworksltd/github-exporter#8]
I'm providing a `GITHUB_TOKEN`, but it's only showing my org's public repos - is this supported?

Thanks!

**Comment by Rucknar** [comment]
As far as I know the token only allows us to scrape more often. I was considering this the other day actually, it shouldn't be hard to get viability of the private repos. I'll take a look today.

**Comment by Rucknar** [comment]
@hairyhenderson Just pushed up a fix, `:latest` image available on the hub or of course here.
Let me know if that works for you.

**Comment by hairyhenderson** [comment]
Thanks @Rucknar! That was fast :grin: I'll test this out again soon...

**Comment by hairyhenderson** [comment]
Ok, awesome. I can confirm that this is fixed by #9 🎉
